// ─── Données de démonstration (mode hors-ligne) ──────────────────────────────
// Utilisées lorsque VITE_API_URL n'est pas défini. Reprend le jeu de données
// d'amorçage du backend (dlc-api) afin que l'application se comporte comme si
// elle était branchée sur une base fraîchement initialisée.

export const MOCK_USERS = [
  { id: 1, name: "Mario Dumont",    email: "mdupont",   password: "1234",  roles: [] },
  { id: 2, name: "Jean Martin",     email: "jmartin",   password: "1234",  roles: ["A"] },
  { id: 8, name: "Pierre Lefebvre", email: "plefebvre", password: "1234",  roles: ["A"] },
  { id: 3, name: "Sophie Bernard",  email: "sbernard",  password: "1234",  roles: ["B", "D"] },
  { id: 4, name: "Luc Tremblay",    email: "ltremblay", password: "1234",  roles: ["C1"] },
  { id: 6, name: "Paula Gagnon",    email: "pgagnon",   password: "1234",  roles: ["C2"] },
  { id: 7, name: "Michel Caron",    email: "mcaron",    password: "1234",  roles: ["C3"] },
  { id: 5, name: "Admin Système",   email: "admin",     password: "admin", roles: ["D", "A", "B", "C1", "C2", "C3"] },
];

export const MOCK_SETTINGS = {
  activeForms: { achat: true, activite: true, requisition: true },
  statusDefinitions: {
    soumise:               "Demande envoyée à la direction répondante",
    acceptee:              "Demande acceptée par votre direction répondante et envoyée à la gestionnaire administrative",
    validee:               "Demande acceptée par la gestionnaire administrative et en attente d'être traitée par l'agent administratif",
    commandee:             "Articles commandés — en attente de réception",
    partiellement_traitee: "Certains articles ont été reçus — la demande est en attente de réception complète",
    traitee:               "Demande terminée",
    refusee:               "Demande refusée par la direction ou la gestionnaire administrative",
    annulee:               "Demande annulée par le demandeur ou la demandeuse",
  },
  approbateurRules: [
    { id: 1, approbateurId: 2, matieres: [], niveaux: ["Accueil", "Année transitoire (AT)", "S1", "S2", "S3", "Soutien à l'apprentissage (SA)", "Soutien à l'autonomie et la socialisation (SAS)"] },
    { id: 2, approbateurId: 8, matieres: [], niveaux: ["S4", "S5", "EMS", "Pré-DÉP"] },
  ],
  niveauxList: ["Accueil","Année transitoire (AT)","EMS","Pré-DÉP","S1","S2","S3","S4","S5","Soutien à l'apprentissage (SA)","Soutien à l'autonomie et la socialisation (SAS)","Autre","Non applicable"],
  matieresList: ["Accueil","Adaptation scolaire","Anglais","Arts","Culture et citoyenneté québécoise (CCQ)","Éducation physique","Français","Mathématiques","Science","Univers social / Histoire","Non applicable","Autre"],
  serviceTypes: ["Déménagement de local","Entretien et réparation","Fournitures de bureau","Installation d'équipement","Nettoyage spécial","Travaux d'aménagement","Autres (précisez)"],
};

export const MOCK_REQUESTS = [
  // ── Demandes d'achat ──
  {
    id: 2001, requestNumber: "AM-2026-06-25-001", type: "achat",
    title: "Matériel arts plastiques — rentrée 2026-2027",
    authorId: 1, authorName: "Mario Dumont", date: "2026-06-25", status: "soumise",
    history: [
      { status: "soumise", by: "Mario Dumont", date: "2026-06-25", comment: "" },
    ],
    formData: {
      demandePar: "Mario Dumont", courriel: "mdupont@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-25", dateSouhaitee: "2026-09-01",
      matiere: "Arts", matiereArts: "Plastique", autreArt: "", autreMatiere: "",
      niveau: "S2", autreNiveau: "", directionResponsable: "Jean Martin",
      fournisseurPrincipal: "Dessercom",
      natureActivite: "Réapprovisionnement du matériel d'arts plastiques pour la rentrée 2026-2027.",
      achatPersonnel: "Non", conferencier: "Non", parascolaire: "Non", budgetPassion: "Non",
      total: "348.49 $", _totalNum: 348.49,
      _rows: [
        { id:1, qty:"20", nom:"Pinceaux assortis (set)",         description:"Soies naturelles, tailles 2-12",    numero:"PIN-ASS",  lien:"", prixUnitaire:"3.49",  soustotal:"69.80",  sansTaxe:false },
        { id:2, qty:"12", nom:"Peinture acrylique 500 mL",      description:"Couleurs primaires et secondaires", numero:"ACR-500",  lien:"", prixUnitaire:"8.99",  soustotal:"107.88", sansTaxe:false },
        { id:3, qty:"5",  nom:"Papier aquarelle A2 (bloc 20 f)",description:"300 g/m²",                          numero:"PAQ-A2",  lien:"", prixUnitaire:"12.99", soustotal:"64.95",  sansTaxe:false },
        { id:4, qty:"4",  nom:"Colle blanche 1 L",              description:"",                                  numero:"CB-1L",   lien:"", prixUnitaire:"6.49",  soustotal:"25.96",  sansTaxe:false },
        { id:5, qty:"10", nom:"Carton entoilé 50×65 cm",        description:"Grain fin",                         numero:"CEN-5065",lien:"", prixUnitaire:"7.99",  soustotal:"79.90",  sansTaxe:false },
      ],
    },
  },
  {
    id: 2002, requestNumber: "AM-2026-06-15-001", type: "achat",
    title: "Calculatrices TI-30 — Mathématiques S3/S4",
    authorId: 2, authorName: "Jean Martin", date: "2026-06-15", status: "acceptee",
    history: [
      { status: "soumise",  by: "Jean Martin", date: "2026-06-15", comment: "" },
      { status: "acceptee", by: "Jean Martin", date: "2026-06-16", comment: "Approuvé — remplacement requis avant les examens de fin d'année.", adminComment: "Budget pédagogique S3/S4 disponible." },
    ],
    formData: {
      demandePar: "Jean Martin", courriel: "jmartin@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-15", dateSouhaitee: "2026-08-25",
      matiere: "Mathématiques", matiereArts: "", autreArt: "", autreMatiere: "",
      niveau: "S3", autreNiveau: "", directionResponsable: "Jean Martin",
      fournisseurPrincipal: "Bureau en Gros",
      natureActivite: "Remplacement des calculatrices défectueuses pour 3 classes de mathématiques S3/S4.",
      achatPersonnel: "Non", conferencier: "Non", parascolaire: "Non", budgetPassion: "Non",
      total: "755.55 $", _totalNum: 755.55,
      _rows: [
        { id:1, qty:"28", nom:"Calculatrice TI-30X IIS",          description:"Scientifique approuvée ministère", numero:"TI30XIIS",lien:"", prixUnitaire:"24.99", soustotal:"699.72", sansTaxe:false },
        { id:2, qty:"4",  nom:"Piles AAA (paquet 4)",             description:"Longue durée",                    numero:"PAA-4",   lien:"", prixUnitaire:"5.99",  soustotal:"23.96",  sansTaxe:false },
        { id:3, qty:"1",  nom:"Rangement calculatrices (30 cases)",description:"Cadenas inclus",                 numero:"RNG-30",  lien:"", prixUnitaire:"31.87", soustotal:"31.87",  sansTaxe:false },
      ],
    },
  },
  {
    id: 2003, requestNumber: "AM-2026-06-01-001", type: "achat",
    title: "Matériel de sciences — Chimie S5",
    authorId: 3, authorName: "Sophie Bernard", date: "2026-06-01", status: "validee",
    history: [
      { status: "soumise",  by: "Sophie Bernard",  date: "2026-06-01", comment: "" },
      { status: "acceptee", by: "Pierre Lefebvre", date: "2026-06-03", comment: "Approuvé — budget sciences disponible." },
      { status: "validee",  by: "Sophie Bernard",  date: "2026-06-05", comment: "Vérifiée — Lab-Pro confirme disponibilité pour la mi-août.", adminComment: "" },
    ],
    formData: {
      demandePar: "Sophie Bernard", courriel: "sbernard@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-01", dateSouhaitee: "2026-08-20",
      matiere: "Science", matiereArts: "", autreArt: "", autreMatiere: "",
      niveau: "S5", autreNiveau: "", directionResponsable: "Pierre Lefebvre",
      fournisseurPrincipal: "Lab-Pro",
      natureActivite: "Réapprovisionnement des consommables pour les laboratoires de chimie organique S5.",
      achatPersonnel: "Non", conferencier: "Non", parascolaire: "Non", budgetPassion: "Non",
      total: "612.80 $", _totalNum: 612.80,
      _rows: [
        { id:1, qty:"25", nom:"Lunettes de sécurité anti-buée",  description:"Conformes ANSI Z87.1",             numero:"LS-01",   lien:"", prixUnitaire:"5.99",  soustotal:"149.75", sansTaxe:false, commande:false, recu:false },
        { id:2, qty:"4",  nom:"Brûleur Bunsen gaz naturel",      description:"Avec robinet d'arrêt",             numero:"BB-GN",   lien:"", prixUnitaire:"24.99", soustotal:"99.96",  sansTaxe:false, commande:false, recu:false },
        { id:3, qty:"20", nom:"Béchers 250 mL borosilicate",     description:"Gradués, résistants à la chaleur", numero:"BC-250B", lien:"", prixUnitaire:"8.99",  soustotal:"179.80", sansTaxe:false, commande:false, recu:false },
        { id:4, qty:"3",  nom:"Kit réactifs chimie organique",   description:"Solutions acide/base 500 mL",      numero:"KRCO-3",  lien:"", prixUnitaire:"61.10", soustotal:"183.30", sansTaxe:false, commande:false, recu:false },
      ],
    },
  },
  {
    id: 2004, requestNumber: "AM-2026-05-10-001", type: "achat",
    title: "Romans lecture obligatoire — Français S3",
    authorId: 1, authorName: "Mario Dumont", date: "2026-05-10", status: "commandee",
    history: [
      { status: "soumise",   by: "Mario Dumont",   date: "2026-05-10", comment: "" },
      { status: "acceptee",  by: "Jean Martin",    date: "2026-05-11", comment: "Approuvé." },
      { status: "validee",   by: "Sophie Bernard", date: "2026-05-14", comment: "Vérifiée — Renaud-Bray confirme le stock disponible." },
      { status: "commandee", by: "Luc Tremblay",   date: "2026-05-17", comment: "Commandes passées — livraison estimée fin juin.", adminComment: "Numéro de commande : RB-2026-4477." },
    ],
    formData: {
      demandePar: "Mario Dumont", courriel: "mdupont@csslaval.gouv.qc.ca",
      dateDemande: "2026-05-10", dateSouhaitee: "2026-06-25",
      matiere: "Français", matiereArts: "", autreArt: "", autreMatiere: "",
      niveau: "S3", autreNiveau: "", directionResponsable: "Jean Martin",
      fournisseurPrincipal: "Renaud-Bray",
      natureActivite: "Romans pour les lectures obligatoires de fin d'année — 2 groupes de français S3.",
      achatPersonnel: "Non", conferencier: "Non", parascolaire: "Non", budgetPassion: "Non",
      total: "783.68 $", _totalNum: 783.68,
      _rows: [
        { id:1, qty:"32", nom:"Le Survenant — Germaine Guèvremont",description:"Édition scolaire annotée", numero:"GG-LS",lien:"", prixUnitaire:"11.50", soustotal:"368.00", sansTaxe:true, commande:true,  recu:false },
        { id:2, qty:"32", nom:"Bonheur d'occasion — Gabrielle Roy", description:"Édition scolaire",         numero:"GR-BO",lien:"", prixUnitaire:"12.99", soustotal:"415.68", sansTaxe:true, commande:false, recu:false },
      ],
    },
  },
  {
    id: 2005, requestNumber: "AM-2026-04-05-001", type: "achat",
    title: "Équipement éducation physique — Gymnase",
    authorId: 4, authorName: "Luc Tremblay", date: "2026-04-05", status: "traitee",
    history: [
      { status: "soumise",   by: "Luc Tremblay",    date: "2026-04-05", comment: "" },
      { status: "acceptee",  by: "Pierre Lefebvre", date: "2026-04-07", comment: "Approuvé — budget disponible pour le gymnase." },
      { status: "validee",   by: "Sophie Bernard",  date: "2026-04-09", comment: "Vérifiée — Sport Expert confirme les disponibilités." },
      { status: "commandee", by: "Luc Tremblay",    date: "2026-04-12", comment: "Commande passée chez Sport Expert." },
      { status: "traitee",   by: "Paula Gagnon",    date: "2026-04-25", comment: "Tout reçu et vérifié — matériel distribué au gymnase." },
    ],
    formData: {
      demandePar: "Luc Tremblay", courriel: "ltremblay@csslaval.gouv.qc.ca",
      dateDemande: "2026-04-05", dateSouhaitee: "2026-04-28",
      matiere: "Éducation physique", matiereArts: "", autreArt: "", autreMatiere: "",
      niveau: "Non applicable", autreNiveau: "", directionResponsable: "Pierre Lefebvre",
      fournisseurPrincipal: "Sport Expert",
      natureActivite: "Renouvellement du matériel sportif pour les cours d'éducation physique — tous niveaux.",
      achatPersonnel: "Non", conferencier: "Non", parascolaire: "Non", budgetPassion: "Non",
      total: "573.44 $", _totalNum: 573.44,
      _rows: [
        { id:1, qty:"15", nom:"Ballon de basketball taille 7",  description:"Intérieur, norme officielle", numero:"BB-T7",  lien:"", prixUnitaire:"18.99", soustotal:"284.85", sansTaxe:false, commande:true, recu:true },
        { id:2, qty:"6",  nom:"Filet de badminton double",      description:"Poteaux inclus",              numero:"FBD-6",  lien:"", prixUnitaire:"29.99", soustotal:"179.94", sansTaxe:false, commande:true, recu:true },
        { id:3, qty:"30", nom:"Cônes de signalisation 30 cm",  description:"Assortis, résistants",        numero:"CO-30",  lien:"", prixUnitaire:"0.99",  soustotal:"29.70",  sansTaxe:false, commande:true, recu:true },
        { id:4, qty:"5",  nom:"Sac de rangement en filet (grand)",description:"",                         numero:"SRF-G",  lien:"", prixUnitaire:"15.79", soustotal:"78.95",  sansTaxe:false, commande:true, recu:true },
      ],
    },
  },
  {
    id: 2006, requestNumber: "AM-2026-06-18-001", type: "achat",
    title: "Kits robotique — Technologie S3/S4",
    authorId: 6, authorName: "Paula Gagnon", date: "2026-06-18", status: "refusee",
    history: [
      { status: "soumise", by: "Paula Gagnon", date: "2026-06-18", comment: "" },
      { status: "refusee", by: "Pierre Lefebvre", date: "2026-06-19", comment: "Refusée — du matériel similaire est disponible en entrepôt.", adminComment: "Consulter l'inventaire B-001 avant toute nouvelle commande." },
    ],
    formData: {
      demandePar: "Paula Gagnon", courriel: "pgagnon@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-18", dateSouhaitee: "2026-09-05",
      matiere: "Science", matiereArts: "", autreArt: "", autreMatiere: "Technologie / Robotique",
      niveau: "S3", autreNiveau: "", directionResponsable: "Pierre Lefebvre",
      fournisseurPrincipal: "RobotShop",
      natureActivite: "Achat de kits de robotique pour le cours de programmation S3/S4 — rentrée 2026-2027.",
      achatPersonnel: "Non", conferencier: "Non", parascolaire: "Non", budgetPassion: "Non",
      total: "1 199.70 $", _totalNum: 1199.70,
      _rows: [
        { id:1, qty:"10", nom:"Raspberry Pi 4 Model B (4 GB)", description:"Mini-ordinateur programmable",numero:"RPi4-4G",  lien:"", prixUnitaire:"79.99", soustotal:"799.90", sansTaxe:false },
        { id:2, qty:"10", nom:"Câble HDMI 1,5 m",             description:"",                           numero:"HDMI-15", lien:"", prixUnitaire:"4.99",  soustotal:"49.90",  sansTaxe:false },
        { id:3, qty:"10", nom:"Clavier compact USB (FR-CA)", description:"Compact, résistant",          numero:"CLAV-FR", lien:"", prixUnitaire:"19.99", soustotal:"199.90", sansTaxe:false },
        { id:4, qty:"10", nom:"Boîtier pour Raspberry Pi 4", description:"",                           numero:"BOI-RPi4",lien:"", prixUnitaire:"15.00", soustotal:"150.00", sansTaxe:false },
      ],
    },
  },

  // ── Demandes d'activités et de sorties ──
  {
    id: 2007, requestNumber: "AS-2026-06-25-001", type: "activite",
    title: "Sortie Biodôme de Montréal — Sciences S3",
    authorId: 1, authorName: "Mario Dumont", date: "2026-06-25", status: "soumise",
    history: [
      { status: "soumise", by: "Mario Dumont", date: "2026-06-25", comment: "" },
    ],
    formData: {
      "Nom de l'activité": "Sortie Biodôme — Sciences S3",
      nomActivite: "Sortie Biodôme de Montréal — Sciences S3", typeActivite: "Sortie éducative",
      dateDemande: "2026-06-25",
      datesPrevues: [{ date: "2026-09-17", heureDebut: "09:00", heureFin: "15:30" }],
      description: "Visite guidée du Biodôme pour les groupes S3 : zones climatiques, biodiversité, faune laurentienne.",
      niveauxConcernes: ["S3"], matieresConcernees: ["Science"], groupes: "301, 302, 303",
      directionResponsable: "Jean Martin",
      responsables: [], passion: "Non", passionTypes: [], passionAutres: "",
      obligatoire: "Non", autresClientele: "",
      coutEleve: "15.00", nbEleves: "72", coutAdulte: "0", nbAdultes: "4",
      coutLiberation: "233.34", nbPeriodes: "0", coutTransport: "260.00", autreMontant: "0",
      typeTransport: "Location d'un autobus scolaire ou de ville", autreTransport: "",
      nomEtablissement: "Biodôme de Montréal",
      adresseComplete: "4777 Av. Pierre-De Coubertin, Montréal, QC H1V 1B3",
      personneContact: "Service éducatif — Biodôme", telephone: "(514) 868-3000", poste: "",
      heureDepart: "08:30", heureRetour: "16:30",
    },
  },
  {
    id: 2008, requestNumber: "AS-2026-06-10-001", type: "activite",
    title: "Sortie Vieux-Montréal — Histoire S4",
    authorId: 3, authorName: "Sophie Bernard", date: "2026-06-10", status: "acceptee",
    history: [
      { status: "soumise",  by: "Sophie Bernard",  date: "2026-06-10", comment: "" },
      { status: "acceptee", by: "Pierre Lefebvre", date: "2026-06-12", comment: "Approuvé — excellente activité dans le cadre du programme Passion Histoire." },
    ],
    formData: {
      "Nom de l'activité": "Sortie Vieux-Montréal — Histoire S4",
      nomActivite: "Sortie Vieux-Montréal — Histoire S4", typeActivite: "Sortie éducative",
      dateDemande: "2026-06-10",
      datesPrevues: [{ date: "2026-09-23", heureDebut: "09:00", heureFin: "16:00" }],
      description: "Circuit pédestre guidé dans le Vieux-Montréal : Place d'Armes, Vieux-Port, Château Ramezay.",
      niveauxConcernes: ["S4"], matieresConcernees: ["Univers social / Histoire"], groupes: "401, 402",
      directionResponsable: "Pierre Lefebvre",
      responsables: [{ userId: 2, nom: "Jean Martin", courriel: "jmartin" }],
      passion: "Oui", passionTypes: ["Autres"], passionAutres: "Culture et patrimoine québécois",
      obligatoire: "Non", autresClientele: "",
      coutEleve: "0", nbEleves: "55", coutAdulte: "0", nbAdultes: "3",
      coutLiberation: "233.34", nbPeriodes: "0", coutTransport: "0", autreMontant: "0",
      typeTransport: "Transport en commun", autreTransport: "",
      nomEtablissement: "Vieux-Montréal — Place Jacques-Cartier",
      adresseComplete: "Place Jacques-Cartier, Montréal, QC H2Y 1B6",
      personneContact: "Office du tourisme de Montréal", telephone: "(514) 873-2015", poste: "",
      heureDepart: "08:15", heureRetour: "17:00",
    },
  },
  {
    id: 2009, requestNumber: "AS-2026-05-20-001", type: "activite",
    title: "Sortie Planétarium Rio Tinto Alcan — Sciences S1/S2",
    authorId: 8, authorName: "Pierre Lefebvre", date: "2026-05-20", status: "validee",
    history: [
      { status: "soumise",  by: "Pierre Lefebvre", date: "2026-05-20", comment: "" },
      { status: "acceptee", by: "Pierre Lefebvre", date: "2026-05-21", comment: "Approuvé." },
      { status: "validee",  by: "Sophie Bernard",  date: "2026-05-25", comment: "Vérifiée — transport réservé, billets confirmés.", adminComment: "Référence réservation autobus : TRANS-2026-089." },
    ],
    formData: {
      "Nom de l'activité": "Sortie Planétarium — Sciences S1/S2",
      nomActivite: "Sortie Planétarium Rio Tinto Alcan — Sciences S1/S2", typeActivite: "Sortie éducative",
      dateDemande: "2026-05-20",
      datesPrevues: [{ date: "2026-09-10", heureDebut: "09:00", heureFin: "15:00" }],
      description: "Séance de planétarium (Les Étoiles) + exposition Espace pour les groupes S1/S2.",
      niveauxConcernes: ["S1", "S2"], matieresConcernees: ["Science", "Mathématiques"], groupes: "101, 102, 201, 202",
      directionResponsable: "Pierre Lefebvre",
      responsables: [], passion: "Non", passionTypes: [], passionAutres: "",
      obligatoire: "Non", autresClientele: "",
      coutEleve: "14.50", nbEleves: "84", coutAdulte: "0", nbAdultes: "5",
      coutLiberation: "233.34", nbPeriodes: "0", coutTransport: "290.00", autreMontant: "0",
      typeTransport: "Location d'un autobus scolaire ou de ville", autreTransport: "",
      nomEtablissement: "Planétarium Rio Tinto Alcan",
      adresseComplete: "4801 Av. Pierre-De Coubertin, Montréal, QC H1V 1B3",
      personneContact: "Service aux groupes scolaires", telephone: "(514) 868-3000", poste: "4",
      heureDepart: "08:45", heureRetour: "15:45",
      cpeAuth: { decision: "autorisee", date: "2026-06-28", comment: "Activité approuvée par la CPE — conforme au programme de sciences." },
      ceAuth:  { decision: null, date: "", comment: "" },
    },
  },
  {
    id: 2010, requestNumber: "AS-2026-04-12-001", type: "activite",
    title: "Conférence orientation scolaire — S5",
    authorId: 4, authorName: "Luc Tremblay", date: "2026-04-12", status: "traitee",
    history: [
      { status: "soumise",  by: "Luc Tremblay",   date: "2026-04-12", comment: "" },
      { status: "acceptee", by: "Jean Martin",    date: "2026-04-13", comment: "Approuvé — très pertinent en période d'orientation." },
      { status: "validee",  by: "Sophie Bernard", date: "2026-04-15", comment: "Vérifiée." },
      { status: "traitee",  by: "Luc Tremblay",   date: "2026-05-16", comment: "Conférence complétée — excellent taux de participation (52/54 élèves)." },
    ],
    formData: {
      "Nom de l'activité": "Conférence orientation scolaire",
      nomActivite: "Conférence orientation scolaire — S5", typeActivite: "Conférence",
      dateDemande: "2026-04-12",
      datesPrevues: [{ date: "2026-05-16", heureDebut: "13:00", heureFin: "15:30" }],
      description: "Me Isabelle Fortier (avocate) et M. Carlos Pereira (ingénieur) présentent leurs parcours professionnels aux finissants de S5.",
      niveauxConcernes: ["S5"], matieresConcernees: ["Non applicable"], groupes: "501, 502",
      directionResponsable: "Jean Martin",
      responsables: [], passion: "Non", passionTypes: [], passionAutres: "",
      obligatoire: "Non", autresClientele: "",
      coutEleve: "0", nbEleves: "54", coutAdulte: "0", nbAdultes: "0",
      coutLiberation: "233.34", nbPeriodes: "2", coutTransport: "0", autreMontant: "0",
      typeTransport: "Non applicable", autreTransport: "",
      nomEtablissement: "École — Salle multifonctionnelle", adresseComplete: "",
      personneContact: "Me Isabelle Fortier", telephone: "(450) 555-0143", poste: "",
      heureDepart: "", heureRetour: "",
      cpeAuth: { decision: "autorisee", date: "2026-04-17", comment: "Conférence approuvée par la CPE — contenu pertinent et conférenciers vérifiés." },
      ceAuth:  { decision: "autorisee", date: "2026-04-18", comment: "Autorisée par la CÉ — activité conforme aux orientations pédagogiques de l'école." },
    },
  },
  {
    id: 2011, requestNumber: "AS-2026-06-20-002", type: "activite",
    title: "Spectacle de fin d'année — Tous niveaux",
    authorId: 6, authorName: "Paula Gagnon", date: "2026-06-20", status: "annulee",
    history: [
      { status: "soumise", by: "Paula Gagnon", date: "2026-06-20", comment: "" },
      { status: "annulee", by: "Paula Gagnon", date: "2026-06-22", comment: "Annulée — les locaux prévus ne seront pas disponibles. L'activité sera reportée à l'année prochaine." },
    ],
    formData: {
      "Nom de l'activité": "Spectacle de fin d'année",
      nomActivite: "Spectacle de fin d'année — Tous niveaux", typeActivite: "Activité parascolaire",
      dateDemande: "2026-06-20",
      datesPrevues: [{ date: "2026-06-27", heureDebut: "18:00", heureFin: "21:00" }],
      description: "Spectacle annuel de remise de diplômes et performances artistiques des élèves.",
      niveauxConcernes: ["S1","S2","S3","S4","S5"], matieresConcernees: ["Arts"], groupes: "Tous",
      directionResponsable: "Jean Martin",
      responsables: [], passion: "Non", passionTypes: [], passionAutres: "",
      obligatoire: "Non", autresClientele: "Parents et famille",
      coutEleve: "0", nbEleves: "300", coutAdulte: "0", nbAdultes: "20",
      coutLiberation: "0", nbPeriodes: "0", coutTransport: "0", autreMontant: "0",
      typeTransport: "Non applicable", autreTransport: "",
      nomEtablissement: "École — Amphithéâtre", adresseComplete: "",
      personneContact: "", telephone: "", poste: "", heureDepart: "", heureRetour: "",
    },
  },

  // ── Réquisitions internes ──
  {
    id: 2012, requestNumber: "RI-2026-06-25-001", type: "requisition",
    title: "Déplacement de mobilier — Salle 204",
    authorId: 1, authorName: "Mario Dumont", date: "2026-06-25", status: "acceptee",
    history: [
      { status: "acceptee", by: "Mario Dumont", date: "2026-06-25", comment: "Demande envoyée au vérificateur (réquisition interne)" },
    ],
    formData: {
      titre: "Déplacement de mobilier — Salle 204", typeService: "Déplacement de mobilier",
      priorite: "Normal",
      description: "Déplacer 12 tables et 24 chaises de la salle 204 vers le local 008 avant les travaux de peinture du 29 juin.",
      autreType: "", demandePar: "Mario Dumont", courriel: "mdupont@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-25", dateRealisation: "2026-06-28", localConcerne: "Salle 204 → Local 008",
      drawing: [],
    },
  },
  {
    id: 2013, requestNumber: "RI-2026-06-10-001", type: "requisition",
    title: "Réorganisation entrepôt — B-001",
    authorId: 6, authorName: "Paula Gagnon", date: "2026-06-10", status: "validee_C2",
    history: [
      { status: "acceptee",   by: "Paula Gagnon",  date: "2026-06-10", comment: "Demande envoyée au vérificateur (réquisition interne)" },
      { status: "validee_C2", by: "Sophie Bernard", date: "2026-06-12", comment: "Attribuée au Magasinier — travaux à planifier dès le 17 juin.", adminComment: "" },
    ],
    formData: {
      titre: "Réorganisation entrepôt — B-001", typeService: "Déplacement de mobilier",
      priorite: "Normal",
      description: "Réorganisation complète de l'entrepôt B-001 : déplacement des étagères, tri du matériel, étiquetage des zones thématiques. Durée estimée : 4 heures.",
      autreType: "", demandePar: "Paula Gagnon", courriel: "pgagnon@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-10", dateRealisation: "2026-06-17", localConcerne: "Entrepôt B-001",
      drawing: [],
    },
  },
  {
    id: 2014, requestNumber: "RI-2026-06-01-001", type: "requisition",
    title: "Réparation projecteur — Amphithéâtre",
    authorId: 4, authorName: "Luc Tremblay", date: "2026-06-01", status: "validee_C3",
    history: [
      { status: "acceptee",   by: "Luc Tremblay",  date: "2026-06-01", comment: "Demande envoyée au vérificateur (réquisition interne)" },
      { status: "validee_C3", by: "Sophie Bernard", date: "2026-06-03", comment: "Attribuée au Concierge — Michel Caron disponible dès le 5 juin.", adminComment: "" },
    ],
    formData: {
      titre: "Réparation projecteur — Amphithéâtre", typeService: "Autres (précisez)",
      priorite: "Élevé",
      description: "Projecteur principal hors service (lampe brûlée + ventilation défectueuse). Remplacement requis avant la présentation de fin d'année.",
      autreType: "Réparation équipement audiovisuel",
      demandePar: "Luc Tremblay", courriel: "ltremblay@csslaval.gouv.qc.ca",
      dateDemande: "2026-06-01", dateRealisation: "2026-06-10", localConcerne: "Amphithéâtre — Scène principale",
      drawing: [],
    },
  },
  {
    id: 2015, requestNumber: "RI-2026-04-20-001", type: "requisition",
    title: "Installation étagères — Bibliothèque",
    authorId: 7, authorName: "Michel Caron", date: "2026-04-20", status: "traitee",
    history: [
      { status: "acceptee",   by: "Michel Caron",   date: "2026-04-20", comment: "Demande envoyée au vérificateur (réquisition interne)" },
      { status: "validee_C3", by: "Sophie Bernard",  date: "2026-04-22", comment: "Attribuée au Concierge." },
      { status: "traitee",    by: "Michel Caron",   date: "2026-04-28", comment: "4 étagères installées et fixées. Travaux complétés sans incident." },
    ],
    formData: {
      titre: "Installation étagères — Bibliothèque", typeService: "Déplacement de mobilier",
      priorite: "Faible",
      description: "Installation de 4 nouvelles étagères murales dans la section jeunesse de la bibliothèque pour les nouvelles acquisitions.",
      autreType: "", demandePar: "Michel Caron", courriel: "mcaron@csslaval.gouv.qc.ca",
      dateDemande: "2026-04-20", dateRealisation: "2026-04-28", localConcerne: "Bibliothèque — Section jeunesse",
      drawing: [],
    },
  },
];
